name: Ejecutar Bots de Ezequiel

on:
  schedule:
    # Se ejecuta cada 1 hora para pescar las skins rápido
    - cron: '0 * * * *'
  workflow_dispatch: # Permite ejecutarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar Bot de Cuevana
        run: python bot_cuevana.py

      - name: Ejecutar Bot de Juegos Gratis
        run: python juegos_gratis.py

      - name: Ejecutar Bot de Skins CS
        run: python skins_cs.py

      - name: Actualizar historiales en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add historial.txt historial_juegos.txt historial_skins.txt
          git commit -m "Actualizar memorias de los bots [skip ci]" || echo "Sin cambios"
          git push origin main