name: Bot Multifuncion

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch: # Botón para probarlo manualmente

jobs:
  ejecutar-bots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests beautifulsoup4
      - name: Correr scripts
        run: |
          python bot_cuevana.py
          python juegos_gratis.py
      - name: Actualizar historial en GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add historial.txt historial_juegos.txt
          git commit -m "Update logs [skip ci]" || echo "Sin cambios"
          git push