name: Ejecutar Bots de Ezequiel

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch: # Permite ejecutarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install requests beautifulsoup4

      - name: Ejecutar Bot de Cuevana
        run: python bot_cuevana.py

      - name: Ejecutar Bot de Juegos Gratis
        run: python juegos_gratis.py

      - name: Ejecutar Bot de Skins CS
        run: python skins_cs.py

      - name: Actualizar historiales en GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add historial.txt historial_juegos.txt enviadas.txt historial_skins.txt
          git commit -m "Actualizar memorias de los bots [skip ci]" || echo "Sin cambios"
          git push origin main